<a href="https://colab.research.google.com/github/aso1801002/AI_tech2020/blob/master/20201009AI0205_selectAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##sklernでエラーが出るので、前のバージョンを入れ直す

In [ ]:
##現在のサイキットラーンをアンインストール
!pip uninstall scikit-learn
##前のバージョンを指定してVMにインストール
!pip install scikit-learn==0.20 --ignore-installed

Uninstalling scikit-learn-0.20.0:
  Would remove:
    /usr/local/lib/python3.6/dist-packages/scikit_learn-0.20.0.dist-info/*
    /usr/local/lib/python3.6/dist-packages/sklearn/*
Proceed (y/n)? y
  Successfully uninstalled scikit-learn-0.20.0
  Using cached https://files.pythonhosted.org/packages/0c/b2/05be9b6da9ae4a4c54f537be22e95833f722742a02b1e355fdc09363877c/scikit_learn-0.20.0-cp36-cp36m-manylinux1_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/63/97/af8a92864a04bfa48f1b5c9b1f8bf2ccb2847f24530026f26dd223de4ca0/numpy-1.19.2-cp36-cp36m-manylinux2010_x86_64.whl
  Using cached https://files.pythonhosted.org/packages/8a/14/d0475ceeaa047f3eae2dc7597c3d40228e1d5beee42c1730f3c96ffb5526/scipy-1.5.3-cp36-cp36m-manylinux1_x86_64.whl
ERROR: tensorflow 2.3.0 has requirement numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.2 which is incompatible.
ERROR: tensorflow 2.3.0 has requirement scipy==1.4.1, but you'll have scipy 1.5.3 which is incompatible.
ERROR: datascience 0.10.6

## all_estimators()でループして各種のアルゴリズムで学習させ、比較する

In [ ]:
#ライブラリの読み込み
import pandas as pd
#学習用データとテスト検証用データを分割するライブラリ
from sklearn.model_selection import train_test_split
#正解率を算出するライブラリ
from sklearn.metrics import accuracy_score
# all_estimators(推定器の全てを利用できるようにする)
from sklearn.utils.testing import all_estimators
#警告クラス
import warnings

## webからアヤメのデータを読み込む

In [ ]:
#urlリンクから読み込むライブラリ
import urllib.request as req
#url用の文字列変数を定義
url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/pandas/tests/io/data/csv/iris.csv"
#リンクから保存するためのファイル名を定義
savefile = "iris.csv"
req.urlretrieve(url,savefile)
#pandasのread_csvメソッドを使ってcsvファイルを読み込む
iris_data = pd.read_csv(savefile,encoding="utf-8")
iris_data.head()

SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

##アヤメデータを目的変数yと説明変数xに分類する

In [ ]:
 y = iris_data.loc[ :,"Name"]#目的変数
 x = iris_data.loc[ :, ["SepalLength","SepalWidth","PetalLength","PetalWidth"] ]#説明変数
 print(y.head())
 print(x.head())

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Name, dtype: object
   SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2


##アヤメのデータをさらに学習用とテスト検証用に分離する

In [ ]:
#学習データ（train)とテスト検証用データ(test)に分離
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,train_size=0.8,shuffle=True)
print(x_train.head())
print(y_train.head())
print(x_test.head())
print(y_test.head())

     SepalLength  SepalWidth  PetalLength  PetalWidth
89           5.5         2.5          4.0         1.3
37           4.9         3.1          1.5         0.1
132          6.4         2.8          5.6         2.2
101          5.8         2.7          5.1         1.9
7            5.0         3.4          1.5         0.2
89     Iris-versicolor
37         Iris-setosa
132     Iris-virginica
101     Iris-virginica
7          Iris-setosa
Name: Name, dtype: object
     SepalLength  SepalWidth  PetalLength  PetalWidth
42           4.4         3.2          1.3         0.2
92           5.8         2.6          4.0         1.2
75           6.6         3.0          4.4         1.4
73           6.1         2.8          4.7         1.2
134          6.1         2.6          5.6         1.4
42         Iris-setosa
92     Iris-versicolor
75     Iris-versicolor
73     Iris-versicolor
134     Iris-virginica
Name: Name, dtype: object


##allAlgorithmsにclassifierを指定して「分類」でフィルターした推定器群を取得する

In [ ]:
#推定器のリストをフィルター指定して取得
allAlgorithms = all_estimators(type_filter="classifier")
#ワーニングを無視する
warnings.filterwarnings('ignore')

##推定器のリストをループしながら学習&推論させる

In [ ]:
#推定器のリストをループ
for (name,algorithm) in allAlgorithms:
  try:
   clf = algorithm()
   clf.fit(x_train,y_train)
   y_pred = clf.predict(x_test)
   print(name,"の正解率 =", accuracy_score(y_test,y_pred))

  except Exception as e:
    print("¥033[31m"+"Error:¥033[0m",name,":",e.args)
    #pass
  #else:
    #print("正常系です")

AdaBoostClassifier の正解率 = 0.9
BaggingClassifier の正解率 = 0.9333333333333333
BernoulliNB の正解率 = 0.26666666666666666
CalibratedClassifierCV の正解率 = 0.9333333333333333
ComplementNB の正解率 = 0.6666666666666666
DecisionTreeClassifier の正解率 = 0.9666666666666667
ExtraTreeClassifier の正解率 = 0.9
ExtraTreesClassifier の正解率 = 0.9666666666666667
GaussianNB の正解率 = 0.9333333333333333
GaussianProcessClassifier の正解率 = 0.9666666666666667
GradientBoostingClassifier の正解率 = 0.9666666666666667
KNeighborsClassifier の正解率 = 0.9666666666666667
LabelPropagation の正解率 = 0.9666666666666667
LabelSpreading の正解率 = 0.9666666666666667
LinearDiscriminantAnalysis の正解率 = 0.9333333333333333
LinearSVC の正解率 = 0.9333333333333333
LogisticRegression の正解率 = 0.9666666666666667
LogisticRegressionCV の正解率 = 0.9333333333333333
MLPClassifier の正解率 = 0.9666666666666667
MultinomialNB の正解率 = 0.9
NearestCentroid の正解率 = 0.9666666666666667
NuSVC の正解率 = 0.9666666666666667
PassiveAggressiveClassifier の正解率 = 0.6666666666666666
Perceptron の正解率 = 0.9
Qua

##クロスバリデーション

##クロスバリデーション関連のライブラリのインポート

In [ ]:
#ライブラリのインポート
#K分割のクロスバリデーション（交差検証）のためのライブラリ
from sklearn.model_selection import KFold
#クロスバリデーションスコアを取得するためのオブジェクト
from sklearn.model_selection import cross_val_score

###クロスバリデーションを実行する

In [ ]:
#K分割交差検証用のインスタンスを生成する
kfold_cv = KFold(n_splits=5,shuffle=True )
#すでに生成してあるall_estimatorsのインスタンスをループさせて、クロスバリデーションを行う
for( name,algorithm ) in allAlgorithms:
  try:
    clf = algorithm()
    if hasattr(clf,"score"):
      scores = cross_val_score(clf,x,y,cv=kfold_cv)
      print(name,"の正解率 =")
      print(scores)
  except:
    pass



AdaBoostClassifier の正解率 =
[0.9        0.96666667 0.93333333 0.86666667 0.96666667]
BaggingClassifier の正解率 =
[1.         1.         0.93333333 0.9        0.93333333]
BernoulliNB の正解率 =
[0.3        0.3        0.3        0.26666667 0.23333333]
CalibratedClassifierCV の正解率 =
[0.9        0.96666667 0.86666667 0.93333333 0.93333333]
ComplementNB の正解率 =
[0.7        0.5        0.7        0.73333333 0.7       ]
DecisionTreeClassifier の正解率 =
[0.93333333 0.93333333 1.         0.93333333 0.93333333]
ExtraTreeClassifier の正解率 =
[0.9        0.93333333 0.96666667 0.9        0.93333333]
ExtraTreesClassifier の正解率 =
[0.93333333 0.96666667 0.93333333 0.96666667 0.96666667]
GaussianNB の正解率 =
[0.93333333 0.93333333 0.96666667 0.93333333 1.        ]
GaussianProcessClassifier の正解率 =
[1.         1.         0.96666667 0.93333333 0.93333333]
GradientBoostingClassifier の正解率 =
[0.9        0.96666667 0.93333333 0.93333333 1.        ]
KNeighborsClassifier の正解率 =
[0.96666667 0.93333333 1.         0.96666667 0.93333333

## cross_val_scoreよりもっと詳しい結果を取得できるクロスバリデーション

In [ ]:
#ライブラリのインポート
from sklearn.model_selection import cross_validate

##cross_validateを使ったクロスバリデーション

In [ ]:
#K分割交差検証用のインスタンスを生成する
kfold_cv = KFold(n_splits=5,shuffle=True )
#すでに生成してあるall_estimatorsのインスタンスをループさせて、クロスバリデーションを行う
for( name,algorithm ) in allAlgorithms:
  try:
    clf = algorithm()
    if hasattr(clf,"score"):
      scores = cross_validate(clf,x,y,cv=kfold_cv)
      print(name,"の正解率 =")
      print(scores)
  except:
    pass

AdaBoostClassifier の正解率 =
{'fit_time': array([0.06574988, 0.06221032, 0.06117487, 0.06027865, 0.05936289]), 'score_time': array([0.0056386 , 0.00554085, 0.00558639, 0.00541043, 0.0053978 ]), 'test_score': array([0.9       , 0.93333333, 1.        , 0.9       , 0.9       ]), 'train_score': array([0.975     , 0.96666667, 0.95      , 0.96666667, 0.93333333])}
BaggingClassifier の正解率 =
{'fit_time': array([0.01483583, 0.01263952, 0.01479435, 0.01279116, 0.01262212]), 'score_time': array([0.00165009, 0.00162292, 0.00175285, 0.00171018, 0.00173736]), 'test_score': array([0.93333333, 1.        , 0.93333333, 0.86666667, 1.        ]), 'train_score': array([1.        , 1.        , 1.        , 0.99166667, 1.        ])}
BernoulliNB の正解率 =
{'fit_time': array([0.00294137, 0.00172806, 0.00165391, 0.00166917, 0.00165772]), 'score_time': array([0.00083566, 0.00080585, 0.00077128, 0.00079536, 0.00076628]), 'test_score': array([0.2       , 0.26666667, 0.2       , 0.3       , 0.3       ]), 'train_score': arr

##グリッドサーチで最適なパラメータを探し求める

###ライブラリをimport

In [ ]:
#グリッドサーチのオブジェクトクラスをimport
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

###グリッドサーチを実行してパラメータを試す

In [ ]:
#グリッドサーチで試すパラメータのパターン指定を定義する
parameters = [
              {"C":[1,10,100,1000],"kernel":["linear"] },
              {"C":[1,10,100,1000],"kernel":["rbf"] ,"gamma":[0.001,0.0001] },
              {"C":[1,10,100,1000],"kernel":["sigmoid"],"gamma":[0.001,0.0001]  }
]

clf=SVC()
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
print("普通の学習の正解率 = ",accuracy_score(y_test,y_pred))

# グリッドサーチを行う
kfold_cv = KFold(n_splits=5,shuffle=True )
#グリッドサーチの中でK分割交差検証も行われる
clf_gird = GridSearchCV(SVC(),parameters,cv=kfold_cv)
clf_gird.fit(x_train,y_train)
#学習済みのモデルに最終的に設定された最適と思われるパラメータを表示
print("最適なパラメーター = ",clf_gird.best_estimator_)

#最適なパラメーターで評価
y_pred = clf_gird.predict(x_test)
print("グリッドサーチの正解率 = ",accuracy_score(y_test,y_pred))

普通の学習の正解率 =  0.9666666666666667
最適なパラメーター =  SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)
グリッドサーチの正解率 =  0.9666666666666667


##Numpyの操作確認

In [1]:
import numpy as np

In [3]:
#numpy配列の初期化
a = np.array([1,2,3,4,5]) 
print(a)
#型を表示
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#2次元のnparrayを定義
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
#配列の要素数を指定して0埋めで初期化
print(np.zeros(10))
print(np.zeros((3,2)))
print(np.ones(2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1.]


In [11]:
#連番の配列の要素数を指定して初期化
print(np.arange(5))#0から5未満
print(np.arange(2,9))#2から9未満
print(np.arange(5,8,0.5))#5から8未満 0.5刻み

[0 1 2 3 4]
[2 3 4 5 6 7 8]
[5.  5.5 6.  6.5 7.  7.5]


##numpyで行列計算

In [13]:
a = np.array([1,2,3,4,5])
b = a*2#全ての要素を一度に２倍
print(b)
x=np.arange(10)
print(x)
y=3*x+5
print(y)

[ 2  4  6  8 10]
[0 1 2 3 4 5 6 7 8 9]
[ 5  8 11 14 17 20 23 26 29 32]


In [16]:
#配列の次元数を表示
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [18]:
#Numpy配列で次元数を変換する
a = np.array([[1,2,3],[4,5,6]])
print("a=",a)
b = a.flatten()#フラットにする（１次元配列にする）
print("b=",b)
a = np.array([[1,2,3],[4,5,6]])#2行３列
print(a)
b = a.reshape(3,2)#3行2列に変換（回転）させる
print(b)

a= [[1 2 3]
 [4 5 6]]
b= [1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


##numpyの配列にアクセスする方法

In [23]:
v = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = v[0]
print(a)#２次元配列の１行目
b = v[1:]
print(b)#1行目以降
c = v[:,0]
print(c)#すべての行の0列目

[1 2 3]
[[4 5 6]
 [7 8 9]]
[1 4 7]
